#!python
# -*- python -*-

from IPython.html.notebookapp import NotebookApp
from IPython.config.loader import Config

c = Config()
c.NotebookApp.notebook_manager_class = 'simple_notebook_manager.SimpleNotebookManager'

app = NotebookApp(config=c)
app.initialize(argv=[])
app.start()
